//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWebServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="helloRequest", Namespace="http://learnwebservices.com/services/hello")]
    public partial class helloRequest : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="helloResponse", Namespace="http://learnwebservices.com/services/hello")]
    public partial class helloResponse : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://learnwebservices.com/services/hello", ConfigurationName="LearnWebServices.HelloEndpoint")]
    public interface HelloEndpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LearnWebServices.SayHelloResponse> SayHelloAsync(LearnWebServices.SayHello request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHello
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://learnwebservices.com/services/hello", Order=0)]
        public LearnWebServices.helloRequest HelloRequest;
        
        public SayHello()
        {
        }
        
        public SayHello(LearnWebServices.helloRequest HelloRequest)
        {
            this.HelloRequest = HelloRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://learnwebservices.com/services/hello", Order=0)]
        public LearnWebServices.helloResponse HelloResponse;
        
        public SayHelloResponse()
        {
        }
        
        public SayHelloResponse(LearnWebServices.helloResponse HelloResponse)
        {
            this.HelloResponse = HelloResponse;
        }
    }
}
