//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceReport", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class InvoiceReport : object
    {
        
        private string BillerIDField;
        
        private string TransactionIDField;
        
        private System.DateTime DeliveryDateField;
        
        private string FileTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillerID
        {
            get
            {
                return this.BillerIDField;
            }
            set
            {
                this.BillerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime DeliveryDate
        {
            get
            {
                return this.DeliveryDateField;
            }
            set
            {
                this.DeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadFile", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class DownloadFile : object
    {
        
        private byte[] DataField;
        
        private string FilenameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename
        {
            get
            {
                return this.FilenameField;
            }
            set
            {
                this.FilenameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProtocolReport", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class ProtocolReport : object
    {
        
        private System.DateTime CreateDateField;
        
        private string FileTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class Invoice : object
    {
        
        private string FileTypeField;
        
        private string TransactionIDField;
        
        private byte[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessedInvoice", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class ProcessedInvoice : object
    {
        
        private string FileTypeField;
        
        private System.DateTime SubmitDateField;
        
        private string TransactionIDField;
        
        private string ProcessingStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmitDate
        {
            get
            {
                return this.SubmitDateField;
            }
            set
            {
                this.SubmitDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ProcessingState
        {
            get
            {
                return this.ProcessingStateField;
            }
            set
            {
                this.ProcessingStateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchInvoiceParameter", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class SearchInvoiceParameter : object
    {
        
        private string BillerIDField;
        
        private string TransactionIDField;
        
        private string eBillAccountIDField;
        
        private decimal AmountFromField;
        
        private decimal AmountToField;
        
        private System.Nullable<ServiceReference.State> StateField;
        
        private System.DateTime DeliveryDateFromField;
        
        private System.DateTime DeliveryDateToField;
        
        private System.DateTime PaymentDueDateFromField;
        
        private System.DateTime PaymentDueDateToField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BillerID
        {
            get
            {
                return this.BillerIDField;
            }
            set
            {
                this.BillerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eBillAccountID
        {
            get
            {
                return this.eBillAccountIDField;
            }
            set
            {
                this.eBillAccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal AmountFrom
        {
            get
            {
                return this.AmountFromField;
            }
            set
            {
                this.AmountFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal AmountTo
        {
            get
            {
                return this.AmountToField;
            }
            set
            {
                this.AmountToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<ServiceReference.State> State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime DeliveryDateFrom
        {
            get
            {
                return this.DeliveryDateFromField;
            }
            set
            {
                this.DeliveryDateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime DeliveryDateTo
        {
            get
            {
                return this.DeliveryDateToField;
            }
            set
            {
                this.DeliveryDateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime PaymentDueDateFrom
        {
            get
            {
                return this.PaymentDueDateFromField;
            }
            set
            {
                this.PaymentDueDateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime PaymentDueDateTo
        {
            get
            {
                return this.PaymentDueDateToField;
            }
            set
            {
                this.PaymentDueDateToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/eBill.B2BServiceLib.Logic")]
    public enum State : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Open = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Incomplete = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reported = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unsigned = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Postaldispatched = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Printing = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Return = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notdelivered = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delayed = 67,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchInvoicesResponse", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class SearchInvoicesResponse : object
    {
        
        private int InvoiceCountField;
        
        private int TotalInvoiceCountField;
        
        private ServiceReference.SearchInvoice[] InvoiceListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceCount
        {
            get
            {
                return this.InvoiceCountField;
            }
            set
            {
                this.InvoiceCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalInvoiceCount
        {
            get
            {
                return this.TotalInvoiceCountField;
            }
            set
            {
                this.TotalInvoiceCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ServiceReference.SearchInvoice[] InvoiceList
        {
            get
            {
                return this.InvoiceListField;
            }
            set
            {
                this.InvoiceListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchInvoice", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class SearchInvoice : object
    {
        
        private string BillerIdField;
        
        private string TransactionIdField;
        
        private string eBillAccountIdField;
        
        private System.Nullable<decimal> AmountField;
        
        private ServiceReference.State StateField;
        
        private string PaymentTypeField;
        
        private string ESRReferenceNbrField;
        
        private System.Nullable<System.DateTime> DeliveryDateField;
        
        private System.Nullable<System.DateTime> PaymentDueDateField;
        
        private string ReasonCodeField;
        
        private string ReasonTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillerId
        {
            get
            {
                return this.BillerIdField;
            }
            set
            {
                this.BillerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eBillAccountId
        {
            get
            {
                return this.eBillAccountIdField;
            }
            set
            {
                this.eBillAccountIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ServiceReference.State State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PaymentType
        {
            get
            {
                return this.PaymentTypeField;
            }
            set
            {
                this.PaymentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ESRReferenceNbr
        {
            get
            {
                return this.ESRReferenceNbrField;
            }
            set
            {
                this.ESRReferenceNbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> DeliveryDate
        {
            get
            {
                return this.DeliveryDateField;
            }
            set
            {
                this.DeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.DateTime> PaymentDueDate
        {
            get
            {
                return this.PaymentDueDateField;
            }
            set
            {
                this.PaymentDueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ReasonText
        {
            get
            {
                return this.ReasonTextField;
            }
            set
            {
                this.ReasonTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBillRecipientSubscriptionStatus", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class EBillRecipientSubscriptionStatus : object
    {
        
        private string EbillAccountIDField;
        
        private string EmailAddressField;
        
        private string UIDHRField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EbillAccountID
        {
            get
            {
                return this.EbillAccountIDField;
            }
            set
            {
                this.EbillAccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UIDHR
        {
            get
            {
                return this.UIDHRField;
            }
            set
            {
                this.UIDHRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBillRecipientSubscriptionStatusBulk", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class EBillRecipientSubscriptionStatusBulk : object
    {
        
        private ServiceReference.BillRecipient[] BillRecipientsField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.BillRecipient[] BillRecipients
        {
            get
            {
                return this.BillRecipientsField;
            }
            set
            {
                this.BillRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillRecipient", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class BillRecipient : object
    {
        
        private string EbillAccountIDField;
        
        private string EmailAddressField;
        
        private string UIDHRField;
        
        private ServiceReference.SubmissionStatus SubmissionStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EbillAccountID
        {
            get
            {
                return this.EbillAccountIDField;
            }
            set
            {
                this.EbillAccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UIDHR
        {
            get
            {
                return this.UIDHRField;
            }
            set
            {
                this.UIDHRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public ServiceReference.SubmissionStatus SubmissionStatus
        {
            get
            {
                return this.SubmissionStatusField;
            }
            set
            {
                this.SubmissionStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmissionStatus", Namespace="http://schemas.datacontract.org/2004/07/eBill.B2BServiceLib.Logic")]
    public enum SubmissionStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_ALLOWED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALLOWED = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBillRecipientSubscriptionInitiation", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class EBillRecipientSubscriptionInitiation : object
    {
        
        private string SubscriptionInitiationTokenField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionInitiationToken
        {
            get
            {
                return this.SubscriptionInitiationTokenField;
            }
            set
            {
                this.SubscriptionInitiationTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBillRecipientSubscriptionConfirmation", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class EBillRecipientSubscriptionConfirmation : object
    {
        
        private string EbillAccountIDField;
        
        private string EmailAddressField;
        
        private string UIDHRField;
        
        private ServiceReference.EPartyType TypeField;
        
        private string LanguageField;
        
        private ServiceReference.Party PartyField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EbillAccountID
        {
            get
            {
                return this.EbillAccountIDField;
            }
            set
            {
                this.EbillAccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UIDHR
        {
            get
            {
                return this.UIDHRField;
            }
            set
            {
                this.UIDHRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public ServiceReference.EPartyType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ServiceReference.Party Party
        {
            get
            {
                return this.PartyField;
            }
            set
            {
                this.PartyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Party", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class Party : object
    {
        
        private ServiceReference.Address AddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Address Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPartyType", Namespace="http://schemas.datacontract.org/2004/07/eBill.B2BServiceLib.Logic")]
    public enum EPartyType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRIVATE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMPANY = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class Address : object
    {
        
        private string CompanyNameField;
        
        private string FamilyNameField;
        
        private string GivenNameField;
        
        private string Address1Field;
        
        private string ZIPField;
        
        private string CityField;
        
        private string CountryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FamilyName
        {
            get
            {
                return this.FamilyNameField;
            }
            set
            {
                this.FamilyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName
        {
            get
            {
                return this.GivenNameField;
            }
            set
            {
                this.GivenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ZIP
        {
            get
            {
                return this.ZIPField;
            }
            set
            {
                this.ZIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillerReport", Namespace="http://swisspost_ch.ebs.ebill.b2bservice")]
    public partial class BillerReport : object
    {
        
        private System.DateTime CreateDateField;
        
        private string ReportTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportType
        {
            get
            {
                return this.ReportTypeField;
            }
            set
            {
                this.ReportTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ch.swisspost.ebill.b2bservice", ConfigurationName="ServiceReference.B2BService")]
    public interface B2BService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListBiller", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListBillerResponse")]
        System.Threading.Tasks.Task<ServiceReference.InvoiceReport[]> GetInvoiceListBillerAsync(string BillerID, bool ArchiveData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceBiller", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceBillerResponse")]
        System.Threading.Tasks.Task<ServiceReference.DownloadFile[]> GetInvoiceBillerAsync(string BillerID, string TransactionID, bool BillDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocolList", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocolListResponse")]
        System.Threading.Tasks.Task<ServiceReference.ProtocolReport[]> GetProcessProtocolListAsync(string BillerID, bool ArchiveData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocol", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetProcessProtocolResponse")]
        System.Threading.Tasks.Task<ServiceReference.DownloadFile[]> GetProcessProtocolAsync(string BillerID, System.DateTime CreateDate, bool ArchiveData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocolList", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocolListRespon" +
            "se")]
        System.Threading.Tasks.Task<ServiceReference.ProtocolReport[]> GetRegistrationProtocolListAsync(string BillerID, bool ArchiveData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocol", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetRegistrationProtocolResponse")]
        System.Threading.Tasks.Task<ServiceReference.DownloadFile[]> GetRegistrationProtocolAsync(string BillerID, System.DateTime CreateDate, bool ArchiveData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/UploadFilesReport", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/UploadFilesReportResponse")]
        System.Threading.Tasks.Task<ServiceReference.ProcessedInvoice[]> UploadFilesReportAsync(ServiceReference.Invoice[] invoices, string BillerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/SearchInvoices", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/SearchInvoicesResponse")]
        System.Threading.Tasks.Task<ServiceReference.SearchInvoicesResponse> SearchInvoicesAsync(ServiceReference.SearchInvoiceParameter Parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStat" +
            "us", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStat" +
            "usResponse")]
        System.Threading.Tasks.Task<ServiceReference.EBillRecipientSubscriptionStatus[]> GetEBillRecipientSubscriptionStatusAsync(string BillerID, string RecipientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStat" +
            "usBulk", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetEBillRecipientSubscriptionStat" +
            "usBulkResponse")]
        System.Threading.Tasks.Task<ServiceReference.EBillRecipientSubscriptionStatusBulk> GetEBillRecipientSubscriptionStatusBulkAsync(string BillerID, string[] RecipientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/InitiateEBillRecipientSubscriptio" +
            "n", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/InitiateEBillRecipientSubscriptio" +
            "nResponse")]
        System.Threading.Tasks.Task<ServiceReference.EBillRecipientSubscriptionInitiation> InitiateEBillRecipientSubscriptionAsync(string BillerID, string SubscriptionInitiationEmailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/ConfirmEBillRecipientSubscription" +
            "", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/ConfirmEBillRecipientSubscription" +
            "Response")]
        System.Threading.Tasks.Task<ServiceReference.EBillRecipientSubscriptionConfirmation> ConfirmEBillRecipientSubscriptionAsync(string BillerID, string SubscriptionInitiationToken, string SubscriptionInitiationActivationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReportList", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReportListResponse")]
        System.Threading.Tasks.Task<ServiceReference.BillerReport[]> GetBillerReportListAsync(string BillerID, bool ArchiveData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReport", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetBillerReportResponse")]
        System.Threading.Tasks.Task<ServiceReference.DownloadFile> GetBillerReportAsync(string BillerID, string CreateDate, string FileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoicePayer", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoicePayerResponse")]
        System.Threading.Tasks.Task<ServiceReference.DownloadFile> GetInvoicePayerAsync(string eBillAccountID, string BillerID, string TransactionID, string FileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListPayer", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/GetInvoiceListPayerResponse")]
        System.Threading.Tasks.Task<ServiceReference.InvoiceReport[]> GetInvoiceListPayerAsync(string eBillAccountID, bool ArchiveData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ch.swisspost.ebill.b2bservice/B2BService/ExecutePing", ReplyAction="http://ch.swisspost.ebill.b2bservice/B2BService/ExecutePingResponse")]
        System.Threading.Tasks.Task<string> ExecutePingAsync(string BillerID, string eBillAccountID, System.Nullable<bool> ErrorTest, System.Nullable<bool> ExceptionTest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface B2BServiceChannel : ServiceReference.B2BService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class B2BServiceClient : System.ServiceModel.ClientBase<ServiceReference.B2BService>, ServiceReference.B2BService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public B2BServiceClient() : 
                base(B2BServiceClient.GetDefaultBinding(), B2BServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UserNamePassword.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public B2BServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(B2BServiceClient.GetBindingForEndpoint(endpointConfiguration), B2BServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public B2BServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(B2BServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public B2BServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(B2BServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public B2BServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.InvoiceReport[]> GetInvoiceListBillerAsync(string BillerID, bool ArchiveData)
        {
            return base.Channel.GetInvoiceListBillerAsync(BillerID, ArchiveData);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DownloadFile[]> GetInvoiceBillerAsync(string BillerID, string TransactionID, bool BillDetail)
        {
            return base.Channel.GetInvoiceBillerAsync(BillerID, TransactionID, BillDetail);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ProtocolReport[]> GetProcessProtocolListAsync(string BillerID, bool ArchiveData)
        {
            return base.Channel.GetProcessProtocolListAsync(BillerID, ArchiveData);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DownloadFile[]> GetProcessProtocolAsync(string BillerID, System.DateTime CreateDate, bool ArchiveData)
        {
            return base.Channel.GetProcessProtocolAsync(BillerID, CreateDate, ArchiveData);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ProtocolReport[]> GetRegistrationProtocolListAsync(string BillerID, bool ArchiveData)
        {
            return base.Channel.GetRegistrationProtocolListAsync(BillerID, ArchiveData);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DownloadFile[]> GetRegistrationProtocolAsync(string BillerID, System.DateTime CreateDate, bool ArchiveData)
        {
            return base.Channel.GetRegistrationProtocolAsync(BillerID, CreateDate, ArchiveData);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ProcessedInvoice[]> UploadFilesReportAsync(ServiceReference.Invoice[] invoices, string BillerID)
        {
            return base.Channel.UploadFilesReportAsync(invoices, BillerID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SearchInvoicesResponse> SearchInvoicesAsync(ServiceReference.SearchInvoiceParameter Parameter)
        {
            return base.Channel.SearchInvoicesAsync(Parameter);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.EBillRecipientSubscriptionStatus[]> GetEBillRecipientSubscriptionStatusAsync(string BillerID, string RecipientID)
        {
            return base.Channel.GetEBillRecipientSubscriptionStatusAsync(BillerID, RecipientID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.EBillRecipientSubscriptionStatusBulk> GetEBillRecipientSubscriptionStatusBulkAsync(string BillerID, string[] RecipientID)
        {
            return base.Channel.GetEBillRecipientSubscriptionStatusBulkAsync(BillerID, RecipientID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.EBillRecipientSubscriptionInitiation> InitiateEBillRecipientSubscriptionAsync(string BillerID, string SubscriptionInitiationEmailAddress)
        {
            return base.Channel.InitiateEBillRecipientSubscriptionAsync(BillerID, SubscriptionInitiationEmailAddress);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.EBillRecipientSubscriptionConfirmation> ConfirmEBillRecipientSubscriptionAsync(string BillerID, string SubscriptionInitiationToken, string SubscriptionInitiationActivationCode)
        {
            return base.Channel.ConfirmEBillRecipientSubscriptionAsync(BillerID, SubscriptionInitiationToken, SubscriptionInitiationActivationCode);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.BillerReport[]> GetBillerReportListAsync(string BillerID, bool ArchiveData)
        {
            return base.Channel.GetBillerReportListAsync(BillerID, ArchiveData);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DownloadFile> GetBillerReportAsync(string BillerID, string CreateDate, string FileType)
        {
            return base.Channel.GetBillerReportAsync(BillerID, CreateDate, FileType);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.DownloadFile> GetInvoicePayerAsync(string eBillAccountID, string BillerID, string TransactionID, string FileType)
        {
            return base.Channel.GetInvoicePayerAsync(eBillAccountID, BillerID, TransactionID, FileType);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.InvoiceReport[]> GetInvoiceListPayerAsync(string eBillAccountID, bool ArchiveData)
        {
            return base.Channel.GetInvoiceListPayerAsync(eBillAccountID, ArchiveData);
        }
        
        public System.Threading.Tasks.Task<string> ExecutePingAsync(string BillerID, string eBillAccountID, System.Nullable<bool> ErrorTest, System.Nullable<bool> ExceptionTest)
        {
            return base.Channel.ExecutePingAsync(BillerID, eBillAccountID, ErrorTest, ExceptionTest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserNamePassword))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.TransportWithMessageCredential;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                result.Security.Message.ClientCredentialType = System.ServiceModel.MessageCredentialType.UserName;
                result.Security.Message.EstablishSecurityContext = false;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserNamePassword))
            {
                return new System.ServiceModel.EndpointAddress("https://ebill-ki.postfinance.ch/B2BService/B2BService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return B2BServiceClient.GetBindingForEndpoint(EndpointConfiguration.UserNamePassword);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return B2BServiceClient.GetEndpointAddress(EndpointConfiguration.UserNamePassword);
        }
        
        public enum EndpointConfiguration
        {
            
            UserNamePassword,
        }
    }
}
